### ISSUE TITLE
Center README.md Title and badges by converting to HTML with <center> tags

### ISSUE THREAD

**Issue by codereport** [codereport/jsource#10]
Currently, the title and badges in the README.md are left aligned. It would look nicer if it was centered, but this requires switching from markdown to HTML.

**Comment by 96RadhikaJadhav** [comment]
@codereport  Can I work on the issue? Also could you please let me know which all titles and badges we have to center?

**Comment by codereport** [comment]
> @codereport Can I work on the issue? Also could you please let me know which all titles and badges we have to center?

Absolutely! The title and badges are in the [README.md file](https://github.com/codereport/jsource/blob/main/README.md) and correspond to the following lines of markdown.

```
# J: From C to C++20
[![Build Status](https://travis-ci.com/codereport/jsource.svg?branch=main)](https://travis-ci.com/codereport/jsource)
[![contributions welcome](https://img.shields.io/badge/contributions-welcome-brightgreen.svg?style=flat)](https://github.com/dwyl/esta/issues)
[![GitHub followers](https://img.shields.io/github/followers/codereport.svg?style=social&label=Follow&maxAge=2592000)](https://github.com/codereport?tab=followers)
[![GitHub stars](https://img.shields.io/github/stars/codereport/jsource.svg?style=social&label=Star&maxAge=2592000)](https://GitHub.com/codereport/jsource/stargazers/)
[![Twitter](https://img.shields.io/twitter/follow/code_report.svg?style=social&label=@code_report)](https://twitter.com/code_report)
```

**Comment by 96RadhikaJadhav** [comment]
@codereport  I have created a PR. Please let me know if any other changes required.
