### ISSUE TITLE
Document prerequisites for building docs

### ISSUE THREAD

**Issue by juntuu** [codereport/jsource#127]
Building the documentation requires some additional tools and packages. I did not find these documented anywhere in the repo yet.

These could be listed in the `CONTRIBUTING.md`.

**Comment by Sebanisu** [comment]
https://youtu.be/fvzZ2DkmHlY he set it up during this livestream.

**Comment by Sebanisu** [comment]
Trying to build docs: I don't get why it says  /usr/bin/sphinx-build: not found when it's in my PATH in another folder. :/
