### ISSUE TITLE
Reduce Build / Codebase Complexity

### ISSUE THREAD

**Issue by codereport** [codereport/jsource#13]
* [ ] Reduce complexity of build options
   * [x] Remove [blis](https://github.com/flame/blis) (https://github.com/codereport/jsource/pull/69)
   * [x] Remove [SLEEF](https://sleef.org/)
   * [x] Remove AVX
   * [x] Remove Neon
   * [x] Remove SSE41
   * [x] Remove SSE42
   * [x] Remove SSSE3
   * [x] Remove Android
   * [x] Remove Windows (just use [WSL2](https://docs.microsoft.com/en-us/windows/wsl/compare-versions#whats-new-in-wsl-2))
   * [ ] Remove Raspberry Pi (not sure if much to do here)
   * [x] Remove 32 bit support (https://github.com/codereport/jsource/issues/30)
   * [x] Remove big endian support (https://github.com/codereport/jsource/pull/32)
   * [x] Remove `MEMAUDIT` (https://github.com/codereport/jsource/pull/46)
   * [x] Remove `unlikely/likely`
   * [x] Remove `ARGCHK1/2/3`
   * [x] Remove `USEMULTINTRINSIC` (https://github.com/codereport/jsource/pull/49)
   * [x] Remove [AES](https://github.com/codereport/jsource/issues/58) (https://github.com/codereport/jsource/pull/63)
   * [x] Remove hostdefs/netdefs folders (https://github.com/codereport/jsource/pull/66) 
   * [x] Remove [OpenMP](https://www.openmp.org/) (https://github.com/codereport/jsource/pull/73)

**Comment by herwinw** [comment]
`ARGCHK1/2/3` looks to have been removed in commit a5b681991187f0390df614ce7489cde3f0cb649d, that one can be checked off as well
