### ISSUE TITLE
Code example for first 10 odd numbers on APL is incorrect

### ISSUE THREAD

**Issue by herwinw** [codereport/jsource#206]
It looks like `⍳` in APL starts at 1 instead of 0, the code snippet linked in the readme generates the sequence, `3, 5 .. 21`

**Comment by juntuu** [comment]
I think it just assumes [index origin](http://www.microapl.com/apl_help/ch_020_070_380.htm) to be set to zero.
```apl
      ⎕IO←0
      ⍳4
0 1 2 3
```

**Comment by herwinw** [comment]
I tried the [Runnable link](https://tryapl.org/?clear&q=1%2B2%C3%97%E2%8D%B310&run) from the README, that iota is 1-indexed for me. I'm not sure whether that's a global default, or it saves something in cookies which causes the result to differ depending on that.

**Comment by juntuu** [comment]
Since TryAPL has index origin 1 by default, some possible fixes would be:
- Subtract one instead of adding (as the R sample does)
    ```apl
    ¯1+2×⍳10
    ```

- or set the index origin to zero first (the sharable link unfortunately needs to fit on one line)
    ```apl
    ⎕IO←0 ⋄ 1+2×⍳10
    1+2×⍳10 ⊣ ⎕IO←0
    ```

**Comment by codereport** [comment]
We decided to go with `¯1+2×⍳10`. Thanks for pointing this out.
