### ISSUE TITLE
Suggestion. Doxygen comments on code you convert to C++

### ISSUE THREAD

**Issue by Sebanisu** [codereport/jsource#22]
https://codedocs.xyz/
You can link your repo to it and it auto generates the documentation like a CI. Maybe as your converting the code to C++ you can add doxygen comments. Then you can link people to the codedocs site to look things up.

I found out about it in this article: https://vicrucann.github.io/tutorials/quick-cmake-doxygen/
The article tells you how to do this all manually but they did an update at the end to tell about codedocs.

**Comment by codereport** [comment]
This is definitely an interesting idea! I will take a look at doc generation options when we get to the porting.

**Comment by ahmadbeirkdar** [comment]
Doxygen is amazing! Currently using it for a Qt software, and its pretty seamless
