### ISSUE TITLE
Remove `R return` macro

### ISSUE THREAD

**Issue by codereport** [codereport/jsource#41]
In `j.h` on line 888, there is a macro defined for `return`:
```c
#define R               return
```
This should be removed and all instances of `R` replaced with return. 

**Note:** there are ~4000 references to this, so some regex expression like `[^a-zA-Z]R ` will need to be used to find and replace

**Comment by juntuu** [comment]
I actually had this already done locally. I'll double check it and add a PR.

**Comment by codereport** [comment]
> I actually had this already done locally. I'll double check it and add a PR.

Awesome! Looking forward to seeing the PR
