### ISSUE TITLE
Create `unittest` script that runs `.ijs` test file from JConsole

### ISSUE THREAD

**Issue by codereport** [codereport/jsource#45]
Currently, in order to run a test inside `jconsole` you have to type the following:
```ijs
testpath=: '/home/cph/jsource/test/'
0!:0 <testpath,'tsu.ijs'
0!:2 <testpath,'<insert test name>.ijs'
```
If you be nicer if we could just type this:
```ijs
unittest '<insert test name>'
```

**Comment by hermabe** [comment]
This can be done using ctest. Example:
```bash
jsource/build$ ctest -R ^g0$ -C Debug
Test project jsource/build
    Start 1: g0
1/1 Test #1: g0 ...............................   Passed    0.34 sec

100% tests passed, 0 tests failed out of 1

Total Test time (real) =   0.40 sec
```
I couldn't find support for fixed-string search in ctest so had to use regex with anchors. `-V` can be added to get output of test (and some logging from ctest).

**Comment by hermabe** [comment]
One can also run the test script generated by cmake directly: 
```bash
jsource$ build/jsrc/Debug/jconsole build/test/Debug/g0.ijs
```

**Comment by juntuu** [comment]
Manually erasing the name `y` before running the test seems to work

```ijs
unittest =: verb define
  load './test/tsu.ijs'
  testname =. y
  erase <'y'
  RUN1 testname  NB. RUN1 defined in tsu.ijs
)
```

**Comment by codereport** [comment]
ah, i was wondering if there was a way to erase an argument or variable. you are a life safer @juntuu
