### ISSUE TITLE
Remove ARGCHK1/2/3

### ISSUE THREAD

**Issue by codereport** [codereport/jsource#47]
It would be nice if we could remove the following code in `j.h`:
```cpp
#define DEADARG(x)      0
#define ARGCHK1D(x)
#define ARGCHK2D(x,y)

#define ARGCHK1(x)      RZ(x) DEADARG(x);   // bit set in deadbeef
#define ARGCHK2(x,y)    ARGCHK1(x) ARGCHK1(y)
#define ARGCHK3(x,y,z)  ARGCHK1(x) ARGCHK1(y) ARGCHK1(z)
```
and all of the places that call it (~800). 

Not sure it is possible though as some unit tests might be testing failures (so might have to replace with something).

**Comment by ruchikaa123** [comment]
I wanna work on this issue.

**Comment by codereport** [comment]
Anyone is welcome to work on anything! Open a PR and I will review :)

**Comment by ruchikaa123** [comment]
Hii @codereport
I am new to open source. I want to work on it and contribute to it and by doing so I will also get some experience and get familiar with open source so could you please tell me from where I can get the full code to resolve this issue.

**Comment by codereport** [comment]
At 16:00 of livestream 1 I showed how to `git clone` the code: https://youtu.be/afico3BW-Is?t=959

If you google `git cloning github repo` you should be able to find some more detailed instructions.
