### ISSUE TITLE
Remove function argument macros?

### ISSUE THREAD

**Issue by Sebanisu** [codereport/jsource#60]
Maybe it's better to keep these? Till after we replace `A` and `J` names? It bothered me because I was looking for a function definition and it was hidden in a macro.

Known such macros: (using @juntuu's grep)
-  [x] f.c `#define FMTF(f,T)`
-  [x] j.h `#define DF1(f)`
-  [x] j.h `#define DF2(f)`
-  [x] j.h `#define F1(f)`
-  [x] j.h `#define F2(f)`
-  [x] k.c `#define KF1(f)`
-  [x] k.c `#define KF1F(f)`
-  [x] k.c `#define KF2(f)`
-  [x] p.h `#define TACT(f)`
-  [x] rl.c `#define F1X(f)`
-  [x] rl.c `#define DF1X(f)`
-  [x] rl.c `#define F2X(f)`
-  [x] verbs/va.h `#define AHDR1(f,Tz,Tx)`
-  [x] verbs/ve.h `#define ADECL1  AHDR1`
-  [x] verbs/va.h `#define AHDR2(f,Tz,Tx,Ty)`
-  [x] verbs/ve.h `#define ADECL2  AHDR2`
  * The parameter order went from 123 to 231 so that surprised me
-  [x] verbs/va.h `#define AHDRP(f,Tz,Tx)`
-  [x] verbs/ve.h `#define ADECLP  AHDRP`
-  [x] verbs/va.h `#define AHDRR(f,Tz,Tx)`
-  [x] verbs/ve.h `#define ADECLR  AHDRR`
-  [x] verbs/va.h `#define AHDRS(f,Tz,Tx)`
-  [x] verbs/ve.h `#define ADECLS  AHDRS`
  * These last 6 macros were all the same. And the parameter order was reversed. 12 to 21, I hope these order swaps don't bite us. the tests are working.
-  [x] verbs/vg.c `#define GF(f)`
-  [x] verbs/vgcomp.c `#define CF(f)`
-  [x] verbs/vgsort.c `#define SF(f)`
-  [x] verbs/vi.c `#define IOF(f)`
-  [x] verbs/vi.c `#define IOCOLF(f)`
-  [x] verbs/vrep.c `#define REPF(f)`
-  [x] vq.h `#define QF1(f)`
-  [x] vq.h `#define QF2(f)`
-  [x] vx.h `#define XF1(f)`
-  [x] vx.h `#define XF2(f)`
-  [x] vz.h `#define ZF1(f)`
-  [x] vz.h `#define ZF2(f)`
-  [x] wn.c `#define NUMH(f)`

Example from j.h:
```c++
#define F1(f)           A f(J jt,    A w)
#define F2(f)           A f(J jt,A a,A w)
```
In `j.h` there are many of these wrapper macros. They take the name of a function and generate functions with the all same arguments. I'm currently experimenting on a branch of removing `F1`. I'm using a Regex replace:
```regex
(^|[ \t]+)F1\(([^\)]+?)\)
```
to:
```
A $2(J jt, A w)
```

**Comment by codereport** [comment]
If you can do this via regex I will merge it. I think replacing A & J will have to happen gradually.

**Comment by juntuu** [comment]
The following regex can be used to find this kind of definitions, there seems to be total of 30 different.
```sh
grep -rE '^\s*#define\s+\w+\(([^,]+)(,\w*)*\)\s+\w+\s+\1\(' jsrc/
```

**Comment by Sebanisu** [comment]
When I did a replace all the code wouldn't compile anymore. So I'm taking it slow one line at a time. Though I was thinking notepad++ might work better at searching. Clion caps searches at 100 results. Or I could spend an afternoon setting up vscode.

I might use your grep to make a check list on the first post.
