### ISSUE TITLE
Anyone know how to build J IDE?

### ISSUE THREAD

**Issue by codereport** [codereport/jsource#68]
There seems to be an IDE located at `jsource/jlibrary/addons/ide/jhs`. I spent a couple minutes trying to figure out how to build but to no avail. If someone wants to investigate that would be great.

**Comment by juntuu** [comment]
The simples I got it running was
```sh
./build/jsrc/Debug/jconsole ~addons/ide/jhs/config/jhs.cfg
```
which opens the ide in browser, running the server on localhost.

There is some documentation (haven't read much) at https://code.jsoftware.com/wiki/Guides/JHS/Server

Also other available UIs are listed in https://code.jsoftware.com/wiki/Guides#User_Interfaces_to_J with links to relevant documentation.

**Comment by codereport** [comment]
Neat! Got it working! For me the command from the root directory was 
```
./build/jsrc/Debug/jconsole ./jlibrary/addons/ide/jhs/config/jhs.cfg
```
![image](https://user-images.githubusercontent.com/36027403/106218233-f0f43880-61a4-11eb-9a3b-874185c1dc19.png)
