### ISSUE TITLE
Doxygen / Sphinx: Figure out how to get Functions in the Side Bar TOC

### ISSUE THREAD

**Issue by codereport** [codereport/jsource#92]
![image](https://user-images.githubusercontent.com/36027403/106377861-05cff800-636e-11eb-858e-31c8d7c5dff0.png)

Currently algorithms don't show up in the side bar TOC (table of contents) - need to fix this.

**Comment by nathanesau** [comment]
PR:

https://github.com/codereport/jsource/pull/125
